version: "3"
 # Two volumes created for wordpress and mariadb
volumes:
  wordpress:
  maria_db:
  
services:
  keycloak:
    container_name: keycloak
    depends_on:
      - db
    image: quay.io/keycloak/keycloak
    environment:
      # Admin Username and Password
      KEYCLOAK_ADMIN: {$admin}
      KEYCLOAK_ADMIN_PASSWORD: {$password} 
      # Database Setup
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://db:3306/keycloak
      KC_DB_USERNAME: {$username}
      KC_DB_PASSWORD: {$password}
      # Network Setup
      KC_PROXY: edge
      PROXY_ADDRESS_FORWARDING: true
      KC_HTTP_PORT: 8180
      KC_HTTPS_PORT: 8543
    ports:
      - "8180:8180"
      - "8543:8543"
    networks:
      - backend
    volumes:
      - /Backups/1.2/keycloak
    command: ["start-dev"] #, "--optimized"]
  ## Wordpress web server application
  wordpress:
    container_name: wordpress
    image: wordpress:6.2.0-php8.1-apache
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: {$database}
      WORDPRESS_DB_USER: {$username}
      WORDPRESS_DB_PASSWORD: {$password}
    volumes:
      #- ./Backups/wordpress:/var/www/html
      - ./data/wordpress:/var/www/html 
    networks:
      - internal
  # Database which both applications use
  db:
    container_name: db
    image: mariadb:latest
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_USER: {$username}
      MYSQL_PASSWORD: {$password}
      MYSQL_ROOT_PASSWORD: {$root_password}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

  ## Software to access database locally
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: {$root_password}
    networks:
      - internal
